"""empty message

Revision ID: 1f0f4b72ad1e
Revises: 
Create Date: 2022-04-20 15:58:27.870676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0f4b72ad1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('pwd', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carinfo',
    sa.Column('carinfono', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=20), nullable=True),
    sa.Column('car_sell_price', sa.Integer(), nullable=False),
    sa.Column('car_num', sa.String(length=10), nullable=False),
    sa.Column('car_name', sa.String(length=50), nullable=False),
    sa.Column('car_company', sa.String(length=50), nullable=False),
    sa.Column('car_buy_price', sa.Float(), nullable=False),
    sa.Column('car_year', sa.String(length=50), nullable=False),
    sa.Column('car_buytime', sa.String(length=10), nullable=False),
    sa.Column('car_km', sa.Integer(), nullable=False),
    sa.Column('car_fuel', sa.String(length=10), nullable=False),
    sa.Column('car_gear', sa.String(length=10), nullable=False),
    sa.Column('car_size', sa.String(length=10), nullable=False),
    sa.Column('car_cc', sa.Integer(), nullable=False),
    sa.Column('car_color', sa.String(length=10), nullable=False),
    sa.Column('car_tax_count', sa.Integer(), nullable=False),
    sa.Column('car_seize_count', sa.Integer(), nullable=False),
    sa.Column('car_security_count', sa.Integer(), nullable=False),
    sa.Column('car_accident_count', sa.Integer(), nullable=False),
    sa.Column('car_flood_count', sa.Integer(), nullable=False),
    sa.Column('car_change_using_count', sa.Integer(), nullable=False),
    sa.Column('car_change_owner_count', sa.Integer(), nullable=False),
    sa.Column('car_broken', sa.Integer(), nullable=False),
    sa.Column('car_sellarea', sa.String(length=10), nullable=False),
    sa.Column('car_option_sunloop', sa.Integer(), nullable=False),
    sa.Column('car_option_wheel', sa.Integer(), nullable=False),
    sa.Column('car_option_navi', sa.Integer(), nullable=False),
    sa.Column('car_option_light', sa.Integer(), nullable=False),
    sa.Column('car_option_parkingsensor', sa.Integer(), nullable=False),
    sa.Column('car_option_leatherseat', sa.Integer(), nullable=False),
    sa.Column('car_option_hotseat', sa.Integer(), nullable=False),
    sa.Column('car_option_airbag', sa.Integer(), nullable=False),
    sa.Column('car_option_highpass', sa.Integer(), nullable=False),
    sa.Column('car_option_wiper', sa.Integer(), nullable=False),
    sa.Column('car_option_smartkey', sa.Integer(), nullable=False),
    sa.Column('car_option_autoside', sa.Integer(), nullable=False),
    sa.Column('car_option_coolseat', sa.Integer(), nullable=False),
    sa.Column('car_option_tpms', sa.Integer(), nullable=False),
    sa.Column('car_option_bluetooth', sa.Integer(), nullable=False),
    sa.Column('car_option_hothandle', sa.Integer(), nullable=False),
    sa.Column('car_option_aeb', sa.Integer(), nullable=False),
    sa.Column('car_option_ldsw', sa.Integer(), nullable=False),
    sa.Column('car_option_cruise', sa.Integer(), nullable=False),
    sa.Column('car_option_autotrunk', sa.Integer(), nullable=False),
    sa.Column('car_search_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('carinfono'),
    sa.UniqueConstraint('carinfono')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carinfo')
    op.drop_table('member')
    # ### end Alembic commands ###
